name: publish-to-npm
on:
  push:
    branches:
      - publish-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://npm.pkg.github.com'
        scope: '@JamesIves'
        always-auth: true

    - run: npm init --yes
    - run: ls -a

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}