name: publish-to-npm
on:
  release:
    types: [created]
  push: 
    branches:
      - publish-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev

    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'

    - name: Configure git
      run: |
        git config user.email "iam@jamesiv.es"
        git config user.name "James Ives"

    - run: npm install
    - run: npm run-script build
    - run: npm ci

    # # Publish to npm
    # - run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - run: |
        echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
        npm ci
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}

    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    # Publish to GitHub Packages
    - run: npm publish