name: publish-to-npm
on:
  release:
    types: [created]
  push:
    branches:
      - publish-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev

      env:
        NODE_AUTH_TOKEN: ${{ github.token }}

    - name: Configure git
      run: |
        git config user.email "iam@jamesiv.es"
        git config user.name "James Ives"

    - run: npm install
    - run: npm run-script build
    - run: git push
    - run: npm ci
    - run: ls -a

      # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: 12
        registry-url: 'https://npm.pkg.github.com'

    - run: npm ci

    # Publish to GitHub Packages
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}