name: publish-to-npm
on:
  release:
    types: [created]

  push:
    branches:
      - publish-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master
      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@JamesIves'
      - name: Authenticate with GitHub package registry
        run:
          echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >
          ~/.npmrc
          
      - name: Configure git
        run: |
          git config user.email "iam@jamesiv.es"
          git config user.name "James Ives"
      - run: npm install
      - run: npm run-script build
      - run: npm ci

      - name: Publish
        shell: bash
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}