name: publish-to-npm
on:
  release:
    types: [created]
  push:
    branches:
      - publish-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: 12
        registry-url: 'https://npm.pkg.github.com'

    - run: npm init --yes
    - run: ls -a

    # Publish to GitHub Packages
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}